const monthEl = document.querySelector(".date h1");
const fullDateEl = document.querySelector(".date p");
const daysEl = document.querySelector(".days");

//Get the last day of the month (28, 29, 30 or 31)
//Instead of using static - method Date(2023, 6), we use dynamic method - Date(new Date().getFullYear(), new Date().getMonth().getDate())
const lastDay = new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).getDate();

//Get first day of the month...I did -1 because javascript day starts on Sunday, not Monday, hence we subtract one array
const firstDay = new Date(new Date().getFullYear(), new Date().getMonth(), 1).getDay()-1;

// Get current month from the PC
const monthIndex = new Date().getMonth();

//Create an array of months
const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]
//Replace month on html with month from PC
monthEl.innerText = months[monthIndex];

//Get the full date element from PC, and replace with html text
fullDateEl.innerText = new Date().toDateString();

let days = "";

//condition for creading day divs according to number of days in the month
for(i=firstDay; i>0; i--){
    days += `<div class = "empty"></div>`;
}

//condition for setting the current day, to div with class "today"
for(i=1; i<=lastDay; i++){
    if(i === new Date().getDate()){
        days += `<div class="today">${i}</div>`
    }else{
        days += `<div>${i}</div>`;
    }
}

//Changing the html divs to the one generated by javascript
daysEl.innerHTML = days;



